openapi: 3.0.0
servers:
  - url: 'https://api.cluster.dyte.in/v2'
    description: ''
    variables: {}
info:
  version: v2
  title: Dyte v2 Collection
  description: Next generation APIs
  termsOfService: ''
  contact: {}
  license:
    name: ''
paths:
  /livestreams:
    post:
      summary: Create Independent livestream
      requestBody:
        content:
          application/json:
            schema:
              type: object
              x-examples:
                example-1:
                  name: prdmmp-xhycsl-asdf
              properties:
                name:
                  type: string
                  description: Name to be give to livestream
                  pattern: '^[a-zA-Z0-9-_]*$'
                  nullable: true
            examples:
              example-1:
                value:
                  name: prdmmp-xhycsl
        description: ''
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: Basic  MGVlYWE0ODAtZDEwMi00YmEyLTg5ZmEtZWI2YTg1ZGFiZTlkOjZiY2FhYzg1YzIzMzEyMGFhYjVh
      responses:
        '201':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                x-examples: null
                properties:
                  success:
                    type: boolean
                  data:
                    type: object
                    properties:
                      status:
                        type: string
                      name:
                        type: string
                        nullable: true
                      meeting_id:
                        type: string
                        nullable: true
                      ingest_seconds:
                        type: number
                      viewer_seconds:
                        type: number
                      ingest_server:
                        type: string
                      id:
                        type: string
                      stream_key:
                        type: string
                      playback_url:
                        type: string
              examples:
                example-1:
                  value:
                    success: true
                    data:
                      status: OFFLINE
                      name: Livestreaming-Demo
                      meeting_id: null
                      ingest_seconds: 0
                      viewer_seconds: 0
                      ingest_server: 'rtmps://2ec802dd47b0.global-contribute.live-video.net:443/app/'
                      id: 78dd0b50-4147-4bb8-88d3-2ccc2e98bff0
                      stream_key: sk_ap-south-1_BSErwBSdrcWn_0eG01cFGCJcRcCsflOAX3Eu4B3RyRX
                      playback_url: 'https://2ec802dd47b0.ap-south-1.playback.live-video.net/api/video/v1/ap-south-1.944908621410.channel.Jk1l97eJF0ME.m3u8'
      description: |-
        Create a Livestream for the current organization.

        Create credentials for livestreaming independently using {ingest server + stream key} and distribute it freely using playback URL
      tags:
        - LiveStreams
    get:
      summary: Get All LiveStreams Of An Org
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: Basic  NzBjNWQzOTEtNGJhYy00Y2YzLTk5MDctYmVjMjA1Nzk4YWRiOmQyNzBmYjJmOGNiNGUzZWY1MGI1
        - schema:
            type: boolean
            default: false
          in: query
          name: excludeMeetings
          description: Exclude livestreams done for a meeting
        - schema:
            type: integer
          in: query
          name: limit
        - schema:
            type: integer
          in: query
          name: offset
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: object
                x-examples: null
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      limit:
                        type: integer
                      total:
                        type: integer
                      total_count:
                        type: integer
                      page_count:
                        type: integer
                      current_page:
                        type: integer
                      livestreams:
                        type: array
                        items:
                          type: object
                          properties:
                            status:
                              type: string
                            name:
                              type: string
                              nullable: true
                            meeting_id:
                              type: string
                              nullable: true
                            ingest_seconds:
                              type: number
                            viewer_seconds:
                              type: number
                            ingest_server:
                              type: string
                            id:
                              type: string
                            stream_key:
                              type: string
                            playback_url:
                              type: string
              examples:
                example-0:
                  summary: Get All LiveStreams Of An Org Staging Success
                  value:
                    success: true
                    message: ''
                    data:
                      limit: 10
                      total: 17
                      total_count: 17
                      page_count: 2
                      current_page: 1
                      livestreams:
                        - status: OFFLINE
                          name: prdmmp-xhycsl
                          meeting_id: null
                          ingest_seconds: 0
                          viewer_seconds: 0
                          ingest_server: 'rtmps://2ec802dd47b0.global-contribute.live-video.net:443/app/'
                          id: 82e363e9-6ce2-462a-a9e5-37068a729548
                          stream_key: sk_ap-south-1_6z1GZy7HtfQh_9qCdXZVrLV8E2xDxrkPO0uzXSvB2Eg
                          playback_url: 'https://2ec802dd47b0.ap-south-1.playback.live-video.net/api/video/v1/ap-south-1.944908621410.channel.rHYG1VHblte6.m3u8'
      description: 'Get all livestreams created for an organization. Response includes meetings created for an organization and the meetings which are livestreamed by that organization, in order to only get livestreams not associated with a meeting, use query param of excludeMeetings.'
      tags:
        - LiveStreams
  '/meetings/{meetingId}/livestreams':
    post:
      summary: Start LiveStreaming a meeting
      requestBody:
        content:
          application/json:
            schema:
              type: object
              x-examples:
                example-1:
                  name: prdmmp-xhycsl
              properties:
                name:
                  type: string
                  pattern: '^[a-zA-Z0-9-_]*$'
                  nullable: true
            examples:
              example-1:
                value:
                  name: prdmmp-xhycsl
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: Basic  NzBjNWQzOTEtNGJhYy00Y2YzLTk5MDctYmVjMjA1Nzk4YWRiOmQyNzBmYjJmOGNiNGUzZWY1MGI1
      responses:
        '201':
          description: Created
          headers: {}
          content:
            application/json:
              schema:
                type: object
                x-examples: null
                properties:
                  success:
                    type: boolean
                  data:
                    type: object
                    properties:
                      status:
                        type: string
                      name:
                        type: string
                        nullable: true
                      meeting_id:
                        type: string
                      ingest_server:
                        type: string
                      id:
                        type: string
                      stream_key:
                        type: string
                      playback_url:
                        type: string
              examples:
                example-1:
                  value:
                    success: true
                    data:
                      status: OFFLINE
                      name: null
                      meeting_id: 188566bc-8770-4ca0-9eb3-24b594ecaf7e
                      ingest_server: 'rtmps://2ec802dd47b0.global-contribute.live-video.net:443/app/'
                      id: 7088bba8-f522-49a8-b59b-3cd0e946bbb0
                      stream_key: sk_ap-south-1_AfnVpeYZjidO_fBpWKody7sDUOEfy9Zc6XAZegkR0Va
                      playback_url: 'https://2ec802dd47b0.ap-south-1.playback.live-video.net/api/video/v1/ap-south-1.944908621410.channel.rVKA2KM5Lunt.m3u8'
            application/xml:
              schema:
                type: object
                properties: {}
      description: Start livestreaming for the given meeting
      tags:
        - LiveStreams
    get:
      summary: Get all livestreams for a meeting
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: Basic  NzBjNWQzOTEtNGJhYy00Y2YzLTk5MDctYmVjMjA1Nzk4YWRiOmQyNzBmYjJmOGNiNGUzZWY1MGI1
        - schema:
            type: integer
          in: query
          name: limit
        - schema:
            type: integer
          in: query
          name: offset
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: object
                x-examples: null
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  data:
                    type: object
                    properties:
                      limit:
                        type: integer
                      total:
                        type: integer
                      total_count:
                        type: integer
                      page_count:
                        type: integer
                      current_page:
                        type: integer
                      livestreams:
                        type: array
                        items:
                          type: object
                          properties:
                            status:
                              type: string
                            name:
                              type: string
                              nullable: true
                            meeting_id:
                              type: string
                            ingest_seconds:
                              type: number
                            viewer_seconds:
                              type: number
                            ingest_server:
                              type: string
                            id:
                              type: string
                            stream_key:
                              type: string
                            playback_url:
                              type: string
              examples:
                example-0:
                  summary: Get LiveStream From StreamId Success
                  value:
                    success: true
                    message: ''
                    data:
                      limit: 10
                      total: 1
                      total_count: 1
                      page_count: 1
                      curren_page: 1
                      livestreams:
                        - status: OFFLINE
                          name: null
                          meeting_id: 188566bc-8770-4ca0-9eb3-24b594ecaf7e
                          ingest_seconds: 171
                          viewer_seconds: 160.15999992
                          ingest_server: 'rtmps://2ec802dd47b0.global-contribute.live-video.net:443/app/'
                          id: 7088bba8-f522-49a8-b59b-3cd0e946bbb0
                          stream_key: sk_ap-south-1_AfnVpeYZjidO_fBpWKody7sDUOEfy9Zc6XAZegkR0Va
                          playback_url: 'https://2ec802dd47b0.ap-south-1.playback.live-video.net/api/video/v1/ap-south-1.944908621410.channel.rVKA2KM5Lunt.m3u8'
      description: Get details of all livestreams associated with the given meeting
      tags:
        - LiveStreams
    parameters:
      - schema:
          type: string
          format: uuid
        name: meetingId
        in: path
        required: true
        description: Unique id for a meeting
  '/meetings/{meetingId}/active-livestream/stop':
    post:
      summary: Stop LiveStreaming a meeting
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: prdmmp-xhycsl
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: Basic  NzBjNWQzOTEtNGJhYy00Y2YzLTk5MDctYmVjMjA1Nzk4YWRiOmQyNzBmYjJmOGNiNGUzZWY1MGI1
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  data:
                    type: object
                    properties:
                      message:
                        type: string
                x-examples: null
              examples:
                example-1:
                  value:
                    success: true
                    data:
                      message: livestream stopped
      description: Stop an active livestream of a meeting
      tags:
        - LiveStreams
    parameters:
      - schema:
          type: string
          format: uuid
        name: meetingId
        in: path
        required: true
        description: Unique id for a meeting
  '/livestreams/{streamId}':
    get:
      summary: Get LiveStream details from streamId
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: Basic  NzBjNWQzOTEtNGJhYy00Y2YzLTk5MDctYmVjMjA1Nzk4YWRiOmQyNzBmYjJmOGNiNGUzZWY1MGI1
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: object
                x-examples: null
                properties:
                  success:
                    type: boolean
                  data:
                    type: object
                    properties:
                      status:
                        type: string
                      name:
                        type: string
                        nullable: true
                      meeting_id:
                        type: string
                      ingest_seconds:
                        type: number
                      viewer_seconds:
                        type: number
                      ingest_server:
                        type: string
                      id:
                        type: string
                      stream_key:
                        type: string
                      playback_url:
                        type: string
              examples:
                example-1:
                  value:
                    success: true
                    data:
                      status: OFFLINE
                      name: null
                      meeting_id: 188566bc-8770-4ca0-9eb3-24b594ecaf7e
                      ingest_seconds: 171
                      viewer_seconds: 160.15999992
                      ingest_server: 'rtmps://2ec802dd47b0.global-contribute.live-video.net:443/app/'
                      id: 7088bba8-f522-49a8-b59b-3cd0e946bbb0
                      stream_key: sk_ap-south-1_AfnVpeYZjidO_fBpWKody7sDUOEfy9Zc6XAZegkR0Va
                      playback_url: 'https://2ec802dd47b0.ap-south-1.playback.live-video.net/api/video/v1/ap-south-1.944908621410.channel.rVKA2KM5Lunt.m3u8'
      description: Get details about a livestream from it's ID
      tags:
        - LiveStreams
    parameters:
      - schema:
          type: string
          format: uuid
        name: streamId
        in: path
        required: true
        description: Unique  Id  for a livestream
  '/meetings/{meetingId}/active-livestream':
    parameters:
      - schema:
          type: string
          format: uuid
        name: meetingId
        in: path
        required: true
        description: Unique id for a meeting
    get:
      summary: Get active livestream for a meeting
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                x-examples: null
                properties:
                  success:
                    type: boolean
                  data:
                    type: object
                    properties:
                      status:
                        type: string
                      name:
                        type: string
                        nullable: true
                      meeting_id:
                        type: string
                      ingest_seconds:
                        type: integer
                      viewer_seconds:
                        type: integer
                      ingest_server:
                        type: string
                      id:
                        type: string
                      stream_key:
                        type: string
                      playback_url:
                        type: string
              examples:
                example-1:
                  value:
                    success: true
                    data:
                      status: LIVE
                      name: null
                      meeting_id: 188566bc-8770-4ca0-9eb3-24b594ecaf7e
                      ingest_seconds: 0
                      viewer_seconds: 0
                      ingest_server: 'rtmps://2ec802dd47b0.global-contribute.live-video.net:443/app/'
                      id: 7088bba8-f522-49a8-b59b-3cd0e946bbb0
                      stream_key: sk_ap-south-1_AfnVpeYZjidO_fBpWKody7sDUOEfy9Zc6XAZegkR0Va
                      playback_url: 'https://2ec802dd47b0.ap-south-1.playback.live-video.net/api/video/v1/ap-south-1.944908621410.channel.rVKA2KM5Lunt.m3u8'
      operationId: get-v2-meetings-meetingId-active-livestream
      description: Get currently active livestream details for a given meeting
      tags:
        - LiveStreams
      parameters:
        - schema:
            type: string
          in: header
          name: Authorization
  '/meetings/{meetingId}/active-session':
    get:
      summary: Get an active session
      description: Get an ongoing active session of a meeting
      operationId: GetActiveSession
      parameters:
        - $ref: '#/components/parameters/meetingId'
      tags:
        - ActiveSession
      responses:
        '200':
          $ref: '#/components/responses/GetActiveSession'
        '404':
          $ref: '#/components/responses/GetActiveSessionNotFound'
  '/meetings/{meetingId}/active-session/kick':
    post:
      summary: Kick participants from active session
      description: Kick one or more participants using userId or customParticipantId from an active session
      operationId: KickPartcipants
      parameters:
        - $ref: '#/components/parameters/meetingId'
      tags:
        - ActiveSession
      requestBody:
        $ref: '#/components/requestBodies/KickParticipantsBody'
      responses:
        '200':
          $ref: '#/components/responses/KickParticipants'
        '404':
          $ref: '#/components/responses/ParticipantNotFound'
  '/meetings/{meetingId}/active-session/kick-all':
    post:
      summary: Kick all participant
      description: Kick all participants from an active session
      operationId: KickAllParticipants
      parameters:
        - $ref: '#/components/parameters/meetingId'
      tags:
        - ActiveSession
      responses:
        '200':
          $ref: '#/components/responses/KickAllParticipants'
  '/meetings/{meetingId}/active-session/mute':
    post:
      summary: Mute participants of an active session
      description: Mute one or more participants from an active session using userId or customParticipantId
      operationId: MuteParticipants
      parameters:
        - $ref: '#/components/parameters/meetingId'
      tags:
        - ActiveSession
      requestBody:
        $ref: '#/components/requestBodies/KickParticipantsBody'
      responses:
        '200':
          $ref: '#/components/responses/MuteParticipants'
  '/meetings/{meetingId}/active-session/mute-all':
    post:
      summary: Mute all participants
      description: Mute all participants of an active session
      operationId: MuteAllParticipants
      parameters:
        - $ref: '#/components/parameters/meetingId'
      tags:
        - ActiveSession
      requestBody:
        $ref: '#/components/requestBodies/MuteAllParticipantsBody'
      responses:
        '200':
          $ref: '#/components/responses/MuteAllParticipants'
  '/meetings/{meetingId}/active-session/poll':
    post:
      summary: Create a poll
      description: Create a new poll in an active session
      operationId: CreatePoll
      parameters:
        - $ref: '#/components/parameters/meetingId'
      tags:
        - ActiveSession
      requestBody:
        $ref: '#/components/requestBodies/CreatePollBody'
      responses:
        '201':
          $ref: '#/components/responses/CreatePoll'
  /sessions:
    get:
      summary: Get all sessions of an organization.
      description: 'Returns all sessions of an organization. Supports pagination, filtering by status and number of participants, search by sessionId or meeting name and sorting by date.'
      operationId: GetSessions
      tags:
        - Sessions
      parameters:
        - $ref: '#/components/parameters/pageNo'
        - $ref: '#/components/parameters/perPage'
        - $ref: '#/components/parameters/search'
        - $ref: '#/components/parameters/sortOrder'
        - $ref: '#/components/parameters/startTime'
        - $ref: '#/components/parameters/endTime'
        - $ref: '#/components/parameters/participants'
        - $ref: '#/components/parameters/status'
      responses:
        '200':
          $ref: '#/components/responses/GetSessions'
  '/sessions/{sessionId}':
    get:
      summary: Get details about a particular session.
      description: Returns data about particular session including recording data.
      operationId: GetSessionDetails
      tags:
        - Sessions
      parameters:
        - $ref: '#/components/parameters/sessionId'
      responses:
        '200':
          $ref: '#/components/responses/GetSessionDetails'
  '/meetings/{meetingId}/sessions':
    get:
      summary: Get all session of a meeting
      description: 'Returns all current and past sessions of meeting from meetingId'
      operationId: GetMeetingSessions
      tags:
        - Sessions
      parameters:
        - $ref: '#/components/parameters/meetingId'
        - $ref: '#/components/parameters/pageNo'
        - $ref: '#/components/parameters/perPage'
        - $ref: '#/components/parameters/sortOrder'
        - $ref: '#/components/parameters/search'
        - $ref: '#/components/parameters/startTime'
        - $ref: '#/components/parameters/endTime'
        - $ref: '#/components/parameters/participants'
        - $ref: '#/components/parameters/status'
      responses:
        '200':
          $ref: '#/components/responses/GetSessions'
  '/sessions/{sessionId}/participants':
    get:
      summary: Get participants list of a session
      description: 'Returns participants list that are a part of a given session. Supports pagination, search by participant id and sorting by joined date and duration.'
      operationId: GetSessionParticipants
      tags:
        - Sessions
      parameters:
        - $ref: '#/components/parameters/sessionId'
        - $ref: '#/components/parameters/search'
        - $ref: '#/components/parameters/pageNo'
        - $ref: '#/components/parameters/perPage'
        - $ref: '#/components/parameters/sortOrder'
        - $ref: '#/components/parameters/participantsSortBy'
      responses:
        '200':
          $ref: '#/components/responses/GetSessionParticipants'
  '/sessions/{sessionId}/participants/{participantId}':
    get:
      summary: Get details of a participant.
      description: Returns callstats and general data about a participant.
      operationId: GetParticipantDetails
      tags:
        - Sessions
      parameters:
        - $ref: '#/components/parameters/sessionId'
        - $ref: '#/components/parameters/participantId'
        - $ref: '#/components/parameters/participantFilters'

      responses:
        '200':
          $ref: '#/components/responses/GetParticipantDetails'
  "/sessions/{sessionId}/chat":
    get:
      summary: Fetches all chat message of a session.
      description: Sends download link to download all chat messages of a session in CSV format.
      operationId: GetSessionChat
      tags:
        - Sessions
      parameters:
        - $ref: '#/components/parameters/sessionId'
      responses:
        '200':
          $ref: '#/components/responses/GetSessionChat'
        '404':
          $ref: '#/components/responses/SessionChatNotFound'
components:
  schemas:
    ActiveSession:
      type: object
      properties:
        id:
          type: string
          description: roomUUID of session
        associated_id:
          type: string
          description: 'id of associated object. if session type is meeting, it is mapped to meetingId, livestreamId if session type is livestream'
        type:
          type: string
          description: type of session
          enum:
            - meeting
            - livestream
        status:
          type: string
          description: current status of session
          enum:
            - LIVE
            - ENDED
        live_participants:
          type: number
          description: number of participants currently in the session
        max_concurrent_participants:
          type: number
          description: number of maximum participants that were in the session
        total_participants:
          type: number
          description: number of unique participants that were part of this session.
        minutes_consumed:
          type: number
          description: number of minutes consumed since the session started
        organization_id:
          type: string
          description: Organization id that hosted this session
        started_at:
          type: string
          description: timestamp when session started
        ended_at:
          type: string
          description: timestamp when session ended
        created_at:
          type: string
          description: timestamp when session created
        updated_at:
          type: string
          description: timestamp when session was last updated
        meta:
          type: object
          description: Any meta data about session.
    GenericErrorResponse:
      type: object
      properties:
        success:
          type: boolean
        error:
          type: object
          properties:
            code:
              type: number
            message:
              type: string
    Participant:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        email:
          type: string
        picture:
          type: string
        verified:
          type: boolean
        anonymous:
          type: boolean
        allow_mails:
          type: boolean
        created_at:
          type: string
        updated_at:
          type: string
    Poll:
      type: object
      properties:
        id:
          type: string
        question:
          type: string
        options:
          type: array
          items:
            type: object
            properties:
              text:
                type: string
              count:
                type: number
              votes:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    name:
                      type: string
        anonymous:
          type: boolean
        hide_votes:
          type: boolean
        created_by:
          type: string
        voted:
          type: array
          items:
            type: string
    ParticipantsList:
      type: object
      properties:
        id:
          type: string
          description: Participant ID. This maps to the corresponding peerId.
        user_id:
          type: string
          description: User id for this participant.
        custom_participant_id:
          type: string
          description: ID passed by client to create this participant.
        display_name:
          type: string
          description: Display name of participant when joining the session.
        role:
          type: string
          description: Role of the participant.
        joined_at:
          type: string
          description: timestamp at which participant joined the session.
        left_at:
          type: string
          description: timestamp at which participant left the session.
        duration:
          type: number
          description: number of minutes for which the participant was in the session.
        created_at:
          type: string
          description: timestamp when this participant was created.
        updated_at:
          type: string
          description: timestamp when this participant's data was last updated.
    ParticipantPeerStats:
      type: object
      properties:
        peer_stats:
          type: object
          properties:
            config:
              type: string
            status:
              type: string
            device_info:
              type: object
              properties:
                browser:
                  type: string
                browser_version:
                  type: string
                cpus:
                  type: number
                engine:
                  type: string
                is_mobile:
                  type: boolean
                memory:
                  type: number
                os:
                  type: string
                os_version:
                  type: string
                sdk_name:
                  type: string
                sdk_version:
                  type: string
                user_agent:
                  type: string
                webgl_support:
                  type: string
            events:
              type: array
              items:
                type: object
                properties:
                  timestamp:
                    type: string
                  type:
                    type: string
            ip_information:
              type: object
              properties:
                city:
                  type: string
                country:
                  type: string
                ip_location:
                  type: string
                ipv4:
                  type: string
                org:
                  type: string
                portal:
                  type: string
                region:
                  type: string
                timezone:
                  type: string
            precall_network_information:
              type: object
              properties:
                backend_rtt:
                  type: number
                turn_connectivity:
                  type: boolean
                effective_networktype:
                  type: string
                throughtput:
                  type: number
                jitter:
                  type: number
                rtt:
                  type: number
                reflexive_connectivity:
                  type: boolean
                relay_connectivity:
                  type: boolean
                fractional_loss:
                  type: number
    ParticipantQualityStats:
      type: object
      properties:
        quality_stats:
          type: array
          items:
            type: object
            properties:
              peer_id:
                type: string
              audio_bandwidth:
                type: number
              video_bandwidth:
                type: number
              average_quality:
                type: number
              start:
                type: string
              end:
                type: string
              audio_packet_loss:
                type: number
              video_packet_loss:
                type: number
              audio_stats:
                type: array
                items:
                  type: object
                  properties:
                    timestamp:
                      type: string
                    concealment_events:
                      type: number
                    packets_lost:
                      type: number
                    jitter:
                      type: number
                    quality:
                      type: number
              video_stats:
                type: array
                items:
                  type: object
                  properties:
                    timestamp:
                      type: string
                    frame_width:
                      type: number
                    frame_height:
                      type: number
                    frames_dropped:
                      type: number
                    frames_per_second:
                      type: number
                    packets_lost:
                      type: number
                    jitter:
                      type: number
                    quality:
                      type: number
    ChatMessage: 
      type: object
      properties:
        chat_download_url:
          type: string
        chat_download_url_expiry:
          type: string
  parameters:
    Content-Type:
      name: Content-Type
      in: header
      required: true
      style: simple
      schema:
        type: string
        example: application/json
    streamId:
      name: streamId
      in: path
      required: true
      style: simple
      schema:
        type: number
    meetingId:
      name: meetingId
      in: path
      required: true
      schema:
        type: string
    sessionId:
      name: sessionId
      in: path
      required: true
      schema:
        type: string
    participantId:
      name: participantId
      in: path
      required: true
      schema:
        type: string
    pageNo:
      name: page_no
      in: query
      required: false
      schema:
        type: number
    perPage:
      name: per_page
      in: query
      required: false
      schema:
        type: number
    search:
      name: search
      in: query
      required: false
      schema:
        type: string
    sortOrder:
      name: sort_order
      in: query
      required: false
      schema:
        type: string
        enum:
          - ASC
          - DESC
    startTime:
      name: start_time
      in: query
      required: false
      schema:
        type: string
    endTime:
      name: end_time
      in: query
      required: false
      schema:
        type: string
    participants:
      name: participants
      in: query
      required: false
      schema:
        type: string
      example: '1:10'
    status:
      name: status
      in: query
      required: false
      schema:
        type: string
        enum:
          - LIVE
          - ENDED
    participantsSortBy:
      name: sort_by
      in: query
      schema:
        type: string
        enum:
          - joinedAt
          - duration
    participantFilters:
      name: filters
      description: Add filters to fetch part of the response.
      in: query
      schema:
        type: string
        enum:
          - device_info
          - ip_information
          - precall_network_information
          - events
          - quality_stats
  requestBodies:
    KickParticipantsBody:
      description: Request body for kicking participants from active session. Only one of `participant_id` or `custom_participant_id` is required
      content:
        application/json:
          schema:
            type: object
            properties:
              participant_ids:
                type: array
                items:
                  type: string
              custom_participant_ids:
                type: array
                items:
                  type: string
    MuteAllParticipantsBody:
      description: Request body for muting all participants in an active session.
      content:
        application/json:
          schema:
            type: object
            properties:
              allow_unmute:
                type: boolean
                description: 'if false, participants won''t be able to unmute themselves after they are muted'
    CreatePollBody:
      description: Request body for creating a new poll
      content:
        application/json:
          schema:
            type: object
            properties:
              question:
                type: string
                description: Question of the poll
              options:
                type: array
                description: Different options for the question
                items:
                  type: string
              anonymous:
                type: boolean
                description: if voters on a poll are anonymous
              hide_votes:
                type: boolean
                description: if votes on an option are visible before a person votes
  responses:
    GetActiveSession:
      description: Active Session Success response
      content:
        application/json:
          schema:
            type: object
            properties:
              success:
                type: boolean
              data:
                $ref: '#/components/schemas/ActiveSession'
          examples:
            activeSessionSuccess:
              $ref: '#/components/examples/GetActiveSessionSuccessResponse'
    GetActiveSessionNotFound:
      description: Active Session is not found for the given meetingId
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/GenericErrorResponse'
          examples:
            activeSessionNotFound:
              $ref: '#/components/examples/GetActiveSessionNotFoundResponse'
    KickParticipants:
      description: Kick participants success response
      content:
        application/json:
          schema:
            type: object
            properties:
              success:
                type: boolean
              data:
                type: object
                properties:
                  action:
                    type: string
                  participants:
                    type: array
                    items:
                      $ref: '#/components/schemas/Participant'
    ParticipantNotFound:
      description: No participant found for given `participant_id` or `custom_participant_id`
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/GenericErrorResponse'
          examples:
            participantNotFound:
              $ref: '#/components/examples/ParticipantNotFoundResponse'
    KickAllParticipants:
      description: Kick all participants from a meeeting
      content:
        application/json:
          schema:
            type: object
            properties:
              success:
                type: boolean
              data:
                type: object
                properties:
                  action:
                    type: string
                  kicked_participants_count:
                    type: number
    MuteParticipants:
      description: Mute one or more participants of a meeting
      content:
        application/json:
          schema:
            type: object
            properties:
              success:
                type: boolean
              data:
                type: object
                properties:
                  action:
                    type: string
                  participants:
                    type: array
                    items:
                      $ref: '#/components/schemas/Participant'
    MuteAllParticipants:
      description: Mute all participants of a meeting
      content:
        application/json:
          schema:
            type: object
            properties:
              success:
                type: boolean
              data:
                type: object
                properties:
                  action:
                    type: string
                  muted_participants_count:
                    type: number
    CreatePoll:
      description: response for creating a poll
      content:
        application/json:
          schema:
            type: object
            properties:
              success:
                type: boolean
              data:
                type: object
                properties:
                  action:
                    type: string
                  poll:
                    $ref: '#/components/schemas/Poll'
    GetSessions:
      description: Get all sessions success response
      content:
        application/json:
          schema:
            type: object
            properties:
              success:
                type: boolean
              data:
                type: object
                properties:
                  sessions:
                    type: array
                    items:
                      $ref: '#/components/schemas/ActiveSession'
    GetSessionDetails:
      description: Get details about a particular session
      content:
        application/json:
          schema:
            type: object
            properties:
              success:
                type: boolean
              data:
                type: object
                properties:
                  session:
                    $ref: '#/components/schemas/ActiveSession'
    GetSessionParticipants:
      description: Get participants list of a particular session
      content:
        application/json:
          schema:
            type: object
            properties:
              success:
                type: boolean
              data:
                type: object
                properties:
                  participants:
                    type: array
                    items:
                      $ref: '#/components/schemas/ParticipantsList'
    GetParticipantDetails:
      description: Returns details of a participant along with callstats data.
      content:
        application/json:
          schema:
            type: object
            properties:
              success:
                type: boolean
              data:
                type: object
                properties:
                  participant:
                    allOf:
                      - $ref: '#/components/schemas/ParticipantsList'
                      - $ref: '#/components/schemas/ParticipantPeerStats'
                      - $ref: '#/components/schemas/ParticipantQualityStats'
    GetSessionChat:
      description: Returns all chat messages of a session.
      content:
        application/json:
          schema:
            type: object
            properties:
              success:
                type: boolean
              data:
                type: object 
                $ref: "#/components/schemas/ChatMessage"
    SessionChatNotFound:
      description: No chat dump found for this session.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/GenericErrorResponse'
          examples:
            chatDumpNotFound:
              $ref: '#/components/examples/GetSessionChatNotFoundResponse'
  examples:
    GetActiveSessionSuccessResponse:
      summary: Success response for fetching active session
      value:
        success: true
        data:
          id: 813432c7-3c5a-45e2-9acf-eef7061c7584
          associated_id: 6bf2b8be-04dd-4191-b602-1128921a306b
          type: meeting
          status: LIVE
          live_participants: 1
          max_concurrent_participants: 2
          minutes_consumed: 2.3434
          started_at: '2022-01-12T14:21:34.388Z'
          ended_at: 'null'
          created_at: '2022-01-12T14:21:34.398Z'
          updated_at: '2022-01-12T14:26:00.784Z'
    GetActiveSessionNotFoundResponse:
      summary: Active Session not found
      value:
        success: false
        error:
          code: 404
          message: No active session found for meeting_id 6bf2b8be-04dd-4191-b602-1128921a306b
    ParticipantNotFoundResponse:
      summary: Participant Not Found
      value:
        success: false
        error:
          code: 404
          message: No user found with id 813432c7-3c5a-45e2-9acf-eef7061c7584
    GetSessionChatNotFoundResponse:
      summary: Chat Dump not found
      value:
        success: false
        error:
          code: 404
          message: No chat dump found for this session!
  securitySchemes:
    Authorization:
      type: http
      scheme: basic
      description: |-
        Username is Organization ID
        Password is API Key
tags:
  - name: LiveStreams
  - name: ActiveSession
  - name: Sessions
externalDocs:
  url: ''
  description: ''
security:
  - Authorization: []
